engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
exclude_paths:
- client/__tests__
- client/e2e
- server/tests/
- server/swagger/
- bin/