sudo: required
dist: trusty

language:
  - node_js

node_js:
  - node
  - "6"

services:
  - postgresql

before_script:
  - psql -c 'create database travis;' -U postgres

script:
  - npm test

after_success:
- npm run coveralls