sudo: required
dist: trusty

language:
  - node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database hermes_test;' -U postgres

script:
  - npm test

after_success:
- npm run coveralls