export const ADD_FLASH_MESSAGE = 'ADD FLASH MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const ADD_DOCUMENT_SUCCESS = 'ADD_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const SHOW_ONLY_PUBLIC_DOCUMENTS = 'SHOW_ONLY_PUBLIC_DOCUMENTS';
export const GET_DASHBOARD_DOCUMENT = 'GET_DASHBOARD_DOCUMENT';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_SEARCH_USERS_SUCCESS = 'GET_SEARCH_USERS_SUCCESS';
export const GET_DOCUMENTS_BY_USER_SUCCESS = 'GET_DOCUMENTS_BY_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';

